/**
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Customer {
    id?: number;

    version?: number;

    firstName: string;

    lastName: string;

    telephone?: string;

    email?: string;

    login?: string;

    password: string;

    uuid?: string;

    role?: Customer.RoleEnum;

    dateOfBirth?: Date;

    age?: number;

    homeAddress?: models.Address;

    fullName?: string;

}
export namespace Customer {
    export enum RoleEnum {
        USER = <any> 'USER',
        ADMIN = <any> 'ADMIN'
    }
}
